### ISSUE TITLE
krkba - Integer Overflow in `_startRound` function

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#1]
krkba

high

# Integer Overflow in `_startRound` function

krkba
## Summary
The function uses the `unchecked` keyword to increment `roundId`.
## Vulnerability Detail
`roundId` is calculated by incrementing  `_roundsCount` by 1, and the `unchecked` is used to disable the automatic overflow and underflow checks.
If `_roundsCount` is large(maximum uint256) and incrementing it by 1 will result an overflow, the value of `roundId` will be around to a very small number or zero.
## Impact
Integer overflow can occur other vulnerabilities or it can used by the attacker to minipulate the contract. 
## Code Snippet
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L949-L952
## Tool used

Manual Review

## Recommendation

**Comment by nevillehuang** [comment]
Invalid, overflow is realistically not possible
