### ISSUE TITLE
4b - No Zero address checks implemented when sending `ethAmount` and `dust` to `msg.sender`.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-01-looksrare-judging#104]
4b

medium

# No Zero address checks implemented when sending `ethAmount` and `dust` to `msg.sender`.

## Summary
There are no zero address checks to handle errors when sending the `ethAmount` to msg.sender and `dust` to `msg.sender`.
## Vulnerability Detail
This vulnerability can cause a lock up of funds whenever an attacker uses a zero address or an invalid address. 
## Impact
This can cause a lock up of funds.

## Code Snippet
first  case
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L539-L541

second case
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L633-L635

third case
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L725-L730

## Tool used

Manual Review

## Recommendation
Zero address checks should be implemented before transactions since it is a good practice and should be observed

**Comment by nevillehuang** [comment]
Invalid based on sherlock [rules](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid)

> 3. Zero address checks: Check to make sure input values are not zero addresses.
