### ISSUE TITLE
0xrcontre360 - Block x future rounds with lower than expected ETH

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#105]
0xrcontre360

medium

# Block x future rounds with lower than expected ETH

## Summary
Attacker can block the system for x number of future rounds with only 100 eth

## Vulnerability Detail
When using [depositETHIntoMultipleRounds](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L312) we can create deposits of eth on future rounds. If any of the rounds amount is valid (x % valuePerEntry) and the rest is zero, we can still create all deposits. So we can create one deposit on multiple rounds in the future with only 1 eth, when we should not be able to create multiple deposits with that amount of eth.

If an attacker wants to get x deposits (limited to the block gas limit) he only needs to send 1 value per entry (1 eth), when it should be x eth. He only needs to call the function [depositETHIntoMultipleRounds](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L312) with 1eth as msg.value and an array of zeroes with only 1 element with 1 eth.

Still, these betting positions are worthless, because when calculating the winner the possible numbers to choose as winner will always be above 1, and the fake positions the attacker created are equivalent to 0.

But if the attacker wants to stop the system entirely for the next x rounds, he only needs 100 eth (that he can recover). The max number of deposits is defined by [MAXIMUM_NUMBER_OF_DEPOSITS_PER_ROUND](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L81). Once this number is reached in a round, we cannot deposit more. He only needs to call depositETHIntoMultipleRounds 100 times with 1 eth each call and with an array of length equal to the amount of rounds blocked. This will create 100 deposits on the future rounds avoiding anyone to make more deposits.

The attacker can recover the money on each finished round and repeat the process when getting back the 100 eth.

## Impact
Denial-of-service attack on the system, during an undefined period. With 100eth and 2 addresses (to avoid being blocked because of being the “Same” player).

## Code Snippet
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L81
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1221-L1223
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L312

```solidity
    function depositETHIntoMultipleRounds(uint256[] calldata amounts) external payable nonReentrant whenNotPaused {
        uint256 numberOfRounds = amounts.length;
        if (msg.value == 0 || numberOfRounds == 0) {
            revert ZeroDeposits();
        }

        uint256 startingRoundId = roundsCount;
        Round storage startingRound = rounds[startingRoundId];
        _validateRoundIsOpen(startingRound);

        _setCutoffTimeIfNotSet(startingRound);

        uint256 expectedValue;
        uint256[] memory entriesCounts = new uint256[](numberOfRounds);

        for (uint256 i; i < numberOfRounds; ++i) {
            uint256 roundId = _unsafeAdd(startingRoundId, i);
            Round storage round = rounds[roundId];
            uint256 roundValuePerEntry = round.valuePerEntry;
            if (roundValuePerEntry == 0) {
                (, , roundValuePerEntry) = _writeDataToRound({ roundId: roundId, roundValue: 0 });
            }

            _incrementUserDepositCount(roundId, round);

            uint256 depositAmount = amounts[i];
            if (depositAmount % roundValuePerEntry != 0) {
                revert InvalidValue();
            }
            uint256 entriesCount = _depositETH(round, roundId, roundValuePerEntry, depositAmount);
            expectedValue += depositAmount;

            entriesCounts[i] = entriesCount;
        }

        if (expectedValue != msg.value) {
            revert InvalidValue();
        }

        emit MultipleRoundsDeposited(msg.sender, startingRoundId, amounts, entriesCounts);

        if (
            _shouldDrawWinner(
                startingRound.numberOfParticipants,
                startingRound.maximumNumberOfParticipants,
                startingRound.deposits.length
            )
        ) {
            _drawWinner(startingRound, startingRoundId);
        }
    }


```

## Tool used

Manual Review

## Recommendation
Create a check to verify that the entries count for each one of the deposits is above 1.
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L337-L342
```solidity
            uint256 depositAmount = amounts[i];
            if (depositAmount % roundValuePerEntry != 0) {
                revert InvalidValue();
            }
            if (depositAmount / roundValuePerEntry >= 1) {
                revert InvalidValue();
            }
            uint256 entriesCount = _depositETH(round, roundId, roundValuePerEntry, depositAmount);

```

Duplicate of #18

**Comment by nevillehuang** [comment]
If a player is the only player of a round, it is expected that he will be the winner. Additionally, a winner can only be drawn when a round has 2 players

**Comment by Rcontre360** [comment]
Hi! can I know why is this issue is market as non-reward? if this other issue explains the same bug on the code:

https://github.com/sherlock-audit/2024-01-looksrare-judging/issues/18

Also @nevillehuang  the attacker is being the only player with only 1/x of eth that should be used. Being x the number of rounds he participates with only 1 eth. Also he can just use 2 addresses to bypass the 2 players constraint

**Comment by Rcontre360** [comment]
Also these issues explains the same vulnerability and is market as "Reward"

https://github.com/sherlock-audit/2024-01-looksrare-judging/issues/144
https://github.com/sherlock-audit/2024-01-looksrare-judging/issues/81

**Comment by Rcontre360** [comment]
Escalate
For the reasons I posted in the comments above I think this issue is a valid finding

**Comment by sherlock-admin2** [comment]
> Escalate
> For the reasons I posted in the comments above I think this issue is a valid finding

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by ArnieSec** [comment]
Escalate 

As @Rcontre360 has stated, this issue should be a duplicate of #18 . The root cause is the same and the author of this issue demonstrates how this root cause can be abused to cause a potential indefinite DOS given that the attacker has alot of funds.. 

If we look at sherlocks docs, this therefore qualifies this issue as a valid dupe.
> Scenario A:
There is a root cause/error/vulnerability A in the code. This vulnerability A -> leads to two attack paths:
> - B -> high severity path
> - C -> medium severity attack path/just identifying the vulnerability.
Both B & C would not have been possible if error A did not exist in the first place. In this case, both B & C should be put together as duplicates

@nevillehuang Your comments 
> If a player is the only player of a round, it is expected that he will be the winner. Additionally, a winner can only be drawn when a round has 2 players

Were addressed in the report already in the impact section, which states the use of 2 addresses can be used by the attacker to bypass the "round must have 2 players to call a winner".
>  With 100eth and 2 addresses (to avoid being blocked because of being the “Same” player).

**Comment by sherlock-admin2** [comment]
> Escalate 
> 
> As @Rcontre360 has stated, this issue should be a duplicate of #18 . The root cause is the same and the author of this issue demonstrates how this root cause can be abused to cause a potential indefinite DOS given that the attacker has alot of funds.. 
> 
> If we look at sherlocks docs, this therefore qualifies this issue as a valid dupe.
> > Scenario A:
> There is a root cause/error/vulnerability A in the code. This vulnerability A -> leads to two attack paths:
> > - B -> high severity path
> > - C -> medium severity attack path/just identifying the vulnerability.
> Both B & C would not have been possible if error A did not exist in the first place. In this case, both B & C should be put together as duplicates
> 
> @nevillehuang Your comments 
> > If a player is the only player of a round, it is expected that he will be the winner. Additionally, a winner can only be drawn when a round has 2 players
> 
> Were addressed in the report already in the impact section, which states the use of 2 addresses can be used by the attacker to bypass the "round must have 2 players to call a winner".
> >  With 100eth and 2 addresses (to avoid being blocked because of being the “Same” player).

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@ArnieGod Agree, this should be duplicate of #18, my apologies to the watson @Rcontre360

**Comment by Czar102** [comment]
Planning to consider this issue a duplicate of #18 as proposed by Watsons and the Lead Judge.

**Comment by Rcontre360** [comment]
Thank you guys. Appreciate the extra time for this :pray:

**Comment by Czar102** [comment]
Result:
High
Duplicate of #18

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ArnieGod](https://github.com/sherlock-audit/2024-01-looksrare-judging/issues/105/#issuecomment-1922401370): accepted
