### ISSUE TITLE
0xG0P1 - Deployment in `Linea`  blockchain will not be possible

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#109]
0xG0P1

high

# Deployment in `Linea`  blockchain will not be possible

## Summary
The protocol is designed to be deployed on potentially any EVM-compatible Layer 2 (including ZK L2s). However, assuming deployment on the Linea mainnet, the deployment may not be possible due to the compiler.
## Vulnerability Detail
The protocol is currently utilizing Compiler version `0.8.23`, and there is an expectation to deploy it on `Linea`. However, it's important to note that Linea does not support compiler version `0.8.23`. refer to: https://docs.linea.build/build-on-linea/ethereum-differences. 
## Impact
Deployment will fail on Linea blockchain
## Code Snippet
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L2
## Tool used

Manual Review

## Recommendation
Use Solidity version 0.8.19 or lower and EVM version to `London` for Linea mainnet.

**Comment by 0xhiroshi** [comment]
We think this should be low severity because we can just downgrade Solidity version and it doesn't affect any users

**Comment by nevillehuang** [comment]
@0xhiroshi The following statement in the contest details created some confusion, so I think we should give benefit of the doubt to watson with regards to future integration rules of sherlock. What do you think @Czar102? I think you historically mentioned out of scope configuration of EVM to be not in scope, so I think this is low severity.

> Potentially any EVM compatible L2

**Comment by 0xhiroshi** [comment]
@nevillehuang ok that's fine by me

**Comment by Czar102** [comment]
This is invalid as altering Solidity config fixes this issue.
