### ISSUE TITLE
Anubis - Missing Validation on User Deposits Leading to Potential Denial of Service

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#113]
Anubis

medium

# Missing Validation on User Deposits Leading to Potential Denial of Service

## Summary
The YoloV2 contract allows users to deposit tokens into multiple rounds through the **depositETHIntoMultipleRounds** function without proper validation of the round existence or status. This can potentially allow a denial of service where users can deposit into non-existent or unintended rounds, leading to locked funds or disrupted contract operations.
## Vulnerability Detail
The **depositETHIntoMultipleRounds** function accepts an array of amounts corresponding to different rounds but does not validate if those rounds are valid or in the correct state for deposits. This lack of validation can lead to scenarios where funds are sent to rounds that are not properly initialized or are in a state that should not accept deposits, potentially causing funds to be locked or the contract's intended logic to be disrupted.
## Impact
Users might inadvertently or maliciously deposit ETH into rounds that are not open or do not exist, leading to locked funds or a disrupted contract state. This can result in a denial of service for legitimate users and may require administrative intervention to resolve.
## Code Snippet
Affected function: **depositETHIntoMultipleRounds**

https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L312-L313
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L327-L329
In the code snippet above, the function iterates over the rounds based on the input but does not validate the existence or state of each round.

## Tool used

Manual Review

## Recommendation
Implement rigorous checks to ensure that every round a user attempts to deposit into exists and is in a state that can accept deposits. This can be done by checking the round's status and ensuring it is open before allowing the deposit. Here's a suggested modification:

```solidity
function depositETHIntoMultipleRounds(uint256[] calldata amounts) external payable nonReentrant whenNotPaused {
    uint256 numberOfRounds = amounts.length;
    // ...omitted code...
    for (uint256 i; i < numberOfRounds; ++i) {
        uint256 roundId = _unsafeAdd(startingRoundId, i);
        Round storage round = rounds[roundId];
        require(round.status == RoundStatus.Open, "YoloV2: Round not open for deposits");
        // ...omitted code...
    }
    // ...omitted code...
}
```

**Comment by nevillehuang** [comment]
Invalid, user input error not valid based on sherlock [rules](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid)

> 4. User input validation: User input validation to prevent user mistakes is not considered a valid issue.
