### ISSUE TITLE
Anubis - Improper Access Control in **cancel** Function

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-01-looksrare-judging#114]
Anubis

medium

# Improper Access Control in **cancel** Function

## Summary
The **cancel** function in the YoloV2 contract allows the owner to cancel rounds, but it lacks appropriate checks to prevent the cancellation of rounds that are already closed, potentially leading to unexpected state changes or denial of service.
## Vulnerability Detail
The **cancel** function allows the contract owner to cancel one or more rounds. However, it does not properly check the state of the rounds before performing the cancellation. If the function is called for rounds that are already closed, drawn, or in a state that should not be canceled, it can lead to inconsistencies in the contract state or locked funds.
## Impact
Improper access control and lack of state validation in the **cancel** function can lead to unauthorized state changes. This may result in rounds being canceled unexpectedly, causing confusion, disrupting the normal operation of the contract, and potentially leading to loss or locking of funds.
## Code Snippet
Affected function: **cancel**

https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L429-L430
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L438-L441

In the code snippet above, the function iterates over the rounds based on the input but does not validate the current state of each round before setting their status to **Cancelled**.
## Tool used

Manual Review

## Recommendation
Implement checks to ensure that only rounds that are open and have not been drawn or closed can be canceled. Additionally, consider implementing role-based access control to restrict who can call the **cancel** function. Here's a suggested modification:

```solidity
function cancel(uint256 numberOfRounds) external {
    _validateIsOwner();
    // ...omitted code...
    for (uint256 i; i < numberOfRounds; ++i) {
        uint256 roundId = _unsafeAdd(startingRoundId, i);
        require(rounds[roundId].status == RoundStatus.Open, "YoloV2: Round cannot be canceled");
        rounds[roundId].status = RoundStatus.Cancelled;
    }
    // ...omitted code...
}
```

**Comment by nevillehuang** [comment]
Invalid, similar reasonings to #12
