### ISSUE TITLE
Anubis - Unpredictable Gas Usage in Loops

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-01-looksrare-judging#124]
Anubis

medium

# Unpredictable Gas Usage in Loops

## Summary
The contract contains loops whose iteration count can grow unpredictably based on user behavior. For instance, the **deposit** function iterates over an array of **DepositCalldata**, and the number of iterations depends on the input provided by the user.
## Vulnerability Detail
In the **deposit** function, there's a loop that iterates over the **deposits** array. If this array is large, it could lead to high gas costs, potentially causing transactions to fail due to block gas limits or making the function prohibitively expensive to call.
## Impact
Unpredictable gas costs can lead to denial of service, where users are unable to call the function due to high gas fees. Moreover, if the loop iterates too many times, the transaction may hit the block gas limit and fail, rendering the function unusable.
## Code Snippet
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1089-L1094
## Tool used

Manual Review

## Recommendation
Consider implementing a pattern that limits the number of items processed per transaction. This could involve introducing pagination or limiting the length of the **deposits** array. This ensures that the function's gas usage remains within reasonable bounds and doesn't become a vector for denial of service.

Suggested Fix
Introduce a constant that defines the maximum number of items that can be processed in a single transaction, and enforce this limit in the function logic:

```solidity
uint256 public constant MAX_DEPOSITS_PER_CALL = 10;

function deposit(DepositCalldata[] calldata deposits) external {
    require(deposits.length <= MAX_DEPOSITS_PER_CALL, "Exceeds maximum deposits per call");
    for (uint256 i; i < deposits.length; ++i) {
                DepositCalldata calldata singleDeposit = deposits[i];
                address tokenAddress = singleDeposit.tokenAddress;
                if (isCurrencyAllowed[tokenAddress] != 1) {
                    revert InvalidCollection();
                }
}
```

**Comment by nevillehuang** [comment]
Invalid based on sherlocks [OOG rules](https://docs.sherlock.xyz/audits/judging/judging#viii.-list-of-issue-categories-that-are-considered-valid)

> 4. Out of Gas: Issues that result in Out of Gas errors either by the malicious user filling up the arrays or there is a practical call flow that results in OOG can be considered a valid medium or in cases of blocking all user funds forever maybe a valid high.
Exception: In case the array length is controlled by the trusted admin/owner or the issue describes an impractical usage of parameters to reach OOG state then these submissions would be considered as low.
