### ISSUE TITLE
bareli - _unsafeSubtract can led to error

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-01-looksrare-judging#146]
bareli

medium

# _unsafeSubtract can led to error

## Summary
we are not verifying the _unsafeSubtract implementation as :
  uint256 currentEntryIndex = currentEntryIndexArray[_unsafeSubtract(count, 1)];

## Vulnerability Detail
uint256 currentEntryIndex = currentEntryIndexArray[_unsafeSubtract(count, 1)];
here count can be 0. then we will get an issue.
## Code Snippet
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1286
## Tool used

Manual Review

## Recommendation
verify count is greater than 0.

**Comment by nevillehuang** [comment]
Invalid, count will always be at least 1 or greater than 1, given there must at least be 2 participants per game.
