### ISSUE TITLE
jasonxiale - `YoloV2.cancel(uint256 numberOfRounds)` should add a `startRoundId` parameter or expiration time

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-01-looksrare-judging#148]
jasonxiale

medium

# `YoloV2.cancel(uint256 numberOfRounds)` should add a `startRoundId` parameter or expiration time

## Summary
`YoloV2.cancel(uint256 numberOfRounds)` should add a `startRoundId` parameter or expiration time

## Vulnerability Detail
When [YoloV2.cancel(uint256 numberOfRounds)](https://github.com/sherlock-audit/2024-01-looksrare/blob/7d76b96a58a6aee38f23bb38b8a5daa3bdc03f7c/contracts-yolo/contracts/YoloV2.sol#L428-L446) is executed, the function will cancal `numberOfRounds` of rounds start from [current round](https://github.com/sherlock-audit/2024-01-looksrare/blob/7d76b96a58a6aee38f23bb38b8a5daa3bdc03f7c/contracts-yolo/contracts/YoloV2.sol#L436).
The issue is that a tx can be pending in the mempool for unknown time, so when the `YoloV2.cancal` tx gets executed, the current roundId might be different. 
For example, the owner wants to cancel round in range of [1000, 1005), at the time he submit the tx, the `roundsCount` is 1000, and `numberOfRounds` is 5. But after some pending time in mempool, when the tx gets executed, the `roundsCount` becomes 1500, in such case, [1500, 1505) rounds will be cancelled, which is not correct

## Impact
The wrong rounds will be cancelled.

## Code Snippet
https://github.com/sherlock-audit/2024-01-looksrare/blob/7d76b96a58a6aee38f23bb38b8a5daa3bdc03f7c/contracts-yolo/contracts/YoloV2.sol#L428-L446

## Tool used

Manual Review

## Recommendation
`YoloV2.cancel(uint256 numberOfRounds)` should add a `startRoundId` parameter or expiration time

**Comment by nevillehuang** [comment]
Invalid, admin is trusted to set appropriate gas to cancel rounds and even if it occurs, it is admin breaking assumptions which is invalid based on sherlock [rules, see point 5.](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid). Then users can simply withdraw their deposits for cancelled rounds via `withdrawDeposits()`
