### ISSUE TITLE
bareli - wrong subtraction

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#153]
bareli

medium

# wrong subtraction

## Summary
we should verify that protocolFeeOwed is greater than the msg.value.
## Vulnerability Detail
 protocolFeeOwed -= msg.value;

## Code Snippet
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L524
## Tool used

Manual Review

## Recommendation
use a require statement to verify.

**Comment by nevillehuang** [comment]
Invalid, no explicit check is required to check payment of fees by winner claiming rewards, given there is already inbuilt underflow checks.
