### ISSUE TITLE
kgothatso - ` YoloV2  :: rolloverETH` User can get selected after they moved eth to another rounds  and cause a Dos attack

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-01-looksrare-judging#162]
kgothatso

high

# ` YoloV2  :: rolloverETH` User can get selected after they moved eth to another rounds  and cause a Dos attack

## Summary
 User can get selected after they moved eth to another rounds  and cause a Dos attack 

## Impact
loss of funds
## Code Snippet
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L643
## Tool used

Manual Review

## Recommendation
remove user id from round

**Comment by nevillehuang** [comment]
Invalid, close to zero proof/impact described in this issue
