### ISSUE TITLE
nobody2018 - round.deposits may have duplicate currentEntryIndex

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#17]
nobody2018

medium

# round.deposits may have duplicate currentEntryIndex

## Summary

A malicious user could break the assumption that there are no duplicates of `currentEntryIndex` in `round.deposits` and make these duplicate `Deposit.tokenAmount` be 0 via [[depositETHIntoMultipleRounds](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L312)](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L312). 

## Vulnerability Detail

`depositETHIntoMultipleRounds` is used to deposit ETH into the current round and future rounds, depending on the length of the argument `amounts` array. For example:

If `amounts.length = 2`, then `amounts[0]` is the amount deposited into the current round, and `amounts[1]` is the amount deposited into the next round(current round + 1). And so on.

However, there is a lack of checking whether `amount[i]` is 0 inside the function. The check [[here](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L338)](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L338) does not work for 0, because `0 % roundValuePerEntry = 0`, the check will be bypassed. Let's take a look at the code snippet:

```solidity
File: contracts-yolo\contracts\YoloV2.sol
312:     function depositETHIntoMultipleRounds(uint256[] calldata amounts) external payable nonReentrant whenNotPaused {
313:         uint256 numberOfRounds = amounts.length;
314:->       if (msg.value == 0 || numberOfRounds == 0) {
315:             revert ZeroDeposits();
316:         }
317: 
318:         uint256 startingRoundId = roundsCount;
319:         Round storage startingRound = rounds[startingRoundId];
320:         _validateRoundIsOpen(startingRound);
321: 
322:         _setCutoffTimeIfNotSet(startingRound);
323: 
324:         uint256 expectedValue;
325:         uint256[] memory entriesCounts = new uint256[](numberOfRounds);
326: 
327:         for (uint256 i; i < numberOfRounds; ++i) {
328:             uint256 roundId = _unsafeAdd(startingRoundId, i);
329:             Round storage round = rounds[roundId];
330:             uint256 roundValuePerEntry = round.valuePerEntry;
331:             if (roundValuePerEntry == 0) {
332:                 (, , roundValuePerEntry) = _writeDataToRound({roundId: roundId, roundValue: 0});
333:             }
334: 
335:             _incrementUserDepositCount(roundId, round);
336: 
337:             uint256 depositAmount = amounts[i];
338:->           if (depositAmount % roundValuePerEntry != 0) {
339:                 revert InvalidValue();
340:             }
341:             uint256 entriesCount = _depositETH(round, roundId, roundValuePerEntry, depositAmount);
342:->           expectedValue += depositAmount;
343: 
344:             entriesCounts[i] = entriesCount;
345:         }
346: 
347:->       if (expectedValue != msg.value) {
348:             revert InvalidValue();
349:         }
......
362:     }
```

How to make the `amounts` array contain 0 value and pass the L314 and L347 checks? For example:

```data
amounts[0] = 0
amounts[1] = roundValuePerEntry
msg.value = roundValuePerEntry

expectedValue = amounts[0] + amounts[1] = roundValuePerEntry
```

This will pass all checks. Let us continue to look at L341, what happens when the last argument of `_depositETH(round, roundId, roundValuePerEntry, depositAmount)` is 0? [[_depositETH](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1417-L1455)](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1417-L1455) does not check whether `depositAmount` is 0 internally, and directly pushes the `Deposit` information into the `round.deposits` array. The `currentEntryIndex` obtained [[here](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1428)](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1428) is assigned to new `Deposit.currentEntryIndex`, which is the `currentEntryIndex` of the last `Deposit` of `round.deposits`. Therefore, duplicate `currentEntryIndex` appear and `Deposit.tokenAmount = 0`.

Consider the following scenario:

1.  Alice deposits `roundValuePerEntry` ether into the current round. `round.numberOfParticipants = 1`.
2.  However, when `round.cutoffTime` is about to expire, no one deposits anymore.
3.  Bob noticed this issue and deposited 0 ether into the current round via `depositETHIntoMultipleRounds` (the `amounts` argument is as shown in the previous analysis).
4.  After `round.cutoffTime` passed, [[drawWinner()](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L401-L416)](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L401-L416) is called successfully. Because the number of participants in the current round is 2.
5.  No matter what the random number is, the winner of the current round is Alice. However, **Alice ends up with less ether than `roundValuePerEntry` because she has to pay the fee**. Therefore, she loses funds.

## Impact

- The [[findUpperBound](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/libraries/Arrays.sol#L20)](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/libraries/Arrays.sol#L20) function from the Arrays library is used in [[fulfillRandomWords](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1288)](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1288). The [[comment](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/libraries/Arrays.sol#L17-L18)](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/libraries/Arrays.sol#L17-L18) of the findUpperBound function mentions: **`array` is expected to be sorted in ascending order, and to contain no repeated elements**. This breaks this assumption.
- This report describes a scenario that could trick other users.

## Code Snippet

https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L338

## Tool used

Manual Review

## Recommendation

```solidity
File: contracts-yolo\contracts\YoloV2.sol
1417:     function _depositETH(
1418:         Round storage round,
1419:         uint256 roundId,
1420:         uint256 roundValuePerEntry,
1421:         uint256 depositAmount
1422:     ) private returns (uint256 entriesCount) {
1423:         entriesCount = depositAmount / roundValuePerEntry;
1424:         uint256 roundDepositCount = round.deposits.length;
+++	      require(depositAmount > 0);
```

&nbsp;

Duplicate of #18

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  invalid because { invalid: this is low as its does not show any attack path and thus falls under scenario B of duplication rules; its also a duplicate of 002 issue due to same underlying cause of depositing 0}
