### ISSUE TITLE
itsabinashb - YoloV2.sol::attacker can manipulate `roundDepositCount`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#19]
itsabinashb

medium

# YoloV2.sol::attacker can manipulate `roundDepositCount`

## Summary
`roundDepositCount` was initialized in `_deposit()` of `YoloV2.sol` contract. An attacker can manipulate this by depositing for erc20 with paying some ether as `msg.value`.

## Vulnerability Detail
The `roundDepositCount` was declared in `_deposit` function. First it is initialized with the length of the `deposits` array which is array of `DepositCalldata` struct. Here is the initialization at line-1040:
```solidity
                uint256 roundDepositCount = round.deposits.length;
```
Now if the `msg.value != 0` then `roundDepositCount` is incremented, at line-1079:
```solidity
            unchecked {
                ++roundDepositCount;
            } 
```
And if `deposits.length != 0` and if the token type is ERC-20 then again `roundDepositCount` is incremented, at line-1210: 
```solidity
                    unchecked {
                        ++roundDepositCount;
                    }
```
So if a user create a deposit just with erc-20 token, for example: LOOKS token then it will work fine but if the user adds some `msg.value` to it then it will increment 1 extra time. 
We can reproduce this in test, I added a public variable : `uint256 public roundDepositCount1` in `YoloV2.sol` to hold the latest value
of `roundDepositCount` after all operation in `_deposit()`, like this:
```solidity
  //....rest of codes
                    uint256 depositDataSlotWithCountOffset = _getDepositDataSlotWithCountOffset(
                        roundDepositsLengthSlot,
                        roundDepositCount
                    );
                    _writeDepositorAndCurrentEntryIndexToDeposit(depositDataSlotWithCountOffset, currentEntryIndex);
                    _writeDepositAmountToDeposit(depositDataSlotWithCountOffset, amount);
                    _writeTokenAddressToDeposit(depositDataSlotWithCountOffset, YoloV2__TokenType.ERC20, tokenAddress);
                    unchecked {
                        ++roundDepositCount;
                    }
                } else {
                    revert InvalidTokenType();
                }
            }

            roundDepositCount1 = roundDepositCount;    /// @audit added for testing purpose
            transferManager.transferBatchItemsAcrossCollections(batchTransferItems, msg.sender, address(this));
        }

//...rest of codes
```
Now put this test in `Yolo.deposit.t.sol` contract and run:
```solidity
function test_deposit2() public {
         vm.deal(user3, 10 ether);
        IYoloV2.DepositCalldata[] memory depositsCalldata = _depositCalldata1000LOOKS();
        uint looksAmount = 1000 ether;
        deal(LOOKS, user3, looksAmount);
        _grantApprovalsToTransferManager(user3);

        vm.startPrank(user3);
        IERC20(LOOKS).approve(address(transferManager), looksAmount);

        yolo.deposit{value: 0.01 ether}(1, depositsCalldata);
        uint256 roundDepositCount = yolo.roundDepositCount1();
        console.log(roundDepositCount);
    }
```
The result of this test is:
```solidity
Running 1 test for test/foundry/Yolo.deposit.t.sol:Yolo_Deposit_Test
[PASS] test_deposit2() (gas: 464737)
Logs:
  roundDepositCount is: 2

Test result: ok. 1 passed; 0 failed; 0 skipped; finished in 1.23s
```
You can see how for 1 deposit the deposit count is 2.
But in this case if we don't send ether while calling the `deposit()` it will work correctly, run the test now:
```solidity
function test_deposit2() public {
         vm.deal(user3, 10 ether);
        IYoloV2.DepositCalldata[] memory depositsCalldata = _depositCalldata1000LOOKS();
        uint looksAmount = 1000 ether;
        deal(LOOKS, user3, looksAmount);
        _grantApprovalsToTransferManager(user3);

        vm.startPrank(user3);
        IERC20(LOOKS).approve(address(transferManager), looksAmount);

        yolo.deposit(1, depositsCalldata);  /// @audit now we are not sending ether
        uint256 roundDepositCount = yolo.roundDepositCount1();
        console.log(roundDepositCount);
    }
```
The result is:
```solidity
Running 1 test for test/foundry/Yolo.deposit.t.sol:Yolo_Deposit_Test
[PASS] test_deposit2() (gas: 423559)
Logs:
  roundDepositCount is: 1

Test result: ok. 1 passed; 0 failed; 0 skipped; finished in 1.29s
```
You can see now it is giving correct count.    
Similar issue is present with ERC-721 token type, we wanna create a deposit with erc-721 we will have same issue, run this test:
```solidity
function test_deposit3() public {
        
        address penguOwner = IERC721(PUDGY_PENGUINS).ownerOf(8623);
        vm.deal(penguOwner, 10 ether);
        IYoloV2.DepositCalldata[] memory depositsCalldata = _pudgyPenguinsDepositsCalldata(8_623);

        _grantApprovalsToTransferManager(penguOwner);

        vm.startPrank(penguOwner);
        IERC721(PUDGY_PENGUINS).setApprovalForAll(address(transferManager), true);

        yolo.deposit{value: 0.01 ether}(1, depositsCalldata);
        vm.stopPrank();
        uint256 roundDepositCount = yolo.roundDepositCount1();
        console.log("roundDepositCount is:",roundDepositCount);
    }
```
Result:
```solidity
Running 1 test for test/foundry/Yolo.deposit.t.sol:Yolo_Deposit_Test
[PASS] test_deposit3() (gas: 415821)
Logs:
  roundDepositCount is: 2

Test result: ok. 1 passed; 0 failed; 0 skipped; finished in 1.50s
```
And if we remove the `msg.value` and run the test again the issue will be resolved, the result of this test after removing the `msg.value`:
```solidity
Running 1 test for test/foundry/Yolo.deposit.t.sol:Yolo_Deposit_Test
[PASS] test_deposit3() (gas: 364348)
Logs:
  roundDepositCount is: 1

Test result: ok. 1 passed; 0 failed; 0 skipped; finished in 1.06s
```

## Impact
Attacker can manipulate the `roundDepositCount` by sending ether to the `_deposit()`.

## Code Snippet
1. https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1040
2. https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1079-L1082
3. https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1210-L1212
4. https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1151

## Tool used

Manual Review, Foundry

## Recommendation
Add a require statement, like this: `require(msg.value == 0, "msg.value not allowed")` after [this](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1161) and [this](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1096) line. Custom error can be used instead of `require` statement.

**Comment by nevillehuang** [comment]
Invalid, each deposit occupies one element in the deposits array so if a user deposit ETH and LOOKS it should increase the round deposit count by 2
