### ISSUE TITLE
Anubis - Use of Magic Numbers and Lack of Documentation

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#25]
Anubis

medium

# Use of Magic Numbers and Lack of Documentation

## Summary
The contract uses several constants and magic numbers whose purpose and derivation are not immediately clear from the code, leading to potential misunderstandings or errors in the contract's operation.
## Vulnerability Detail
Constants like **MAXIMUM_PROTOCOL_FEE_BP** are used without clear documentation or justification in the code. This can lead to confusion or misconfiguration, especially when the contract is updated or maintained by different developers.

## Impact
The use of undocumented magic numbers can lead to errors in maintenance or updates, potentially causing financial loss or contract failure.

## Code Snippet
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L76

## Tool used

Manual Review

## Recommendation

1. **Document Constants:** Provide clear, in-line comments explaining the purpose and reason for each constant's value.
2. **Centralize Configuration**: Consider centralizing the contract's configuration settings, making them easier to manage and review.
3. **Use Enumerations for Clarity**: Where appropriate, use enumerations instead of magic numbers to make the code more readable and self-documenting.

**Comment by nevillehuang** [comment]
Invalid, informational finding with no security risk.
