### ISSUE TITLE
Anubis - Access Control and Role Management on interface

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#27]
Anubis

medium

# Access Control and Role Management on interface

## Summary
The contract includes multiple roles with extensive permissions, like **DEFAULT_ADMIN_ROLE** and **OPERATOR**. Proper role management and access control are crucial to prevent unauthorized use or misconfiguration.
## Vulnerability Detail
Mismanagement of roles or unauthorized access to admin functions could lead to contract manipulation, misconfiguration, or unauthorized operations.
## Impact
Unauthorized access to admin functions can lead to misconfiguration, contract manipulation, or disruption, potentially causing financial losses or affecting the contract's integrity.

## Code Snippet
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/interfaces/IYoloV2.sol#L350-L353

https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/interfaces/IYoloV2.sol#L416-L420
## Tool used

Manual Review

## Recommendation

1. **Role Management:** Ensure that roles are assigned and managed securely using the principle of least privilege.
2. **Secure Role-Based Access Control Patterns:** Utilize secure patterns for managing roles and permissions, like OpenZeppelin's AccessControl.
3. **Multi-Signature for Critical Functions:** For extremely sensitive functions, consider implementing multi-signature requirements or timelocks.

**Comment by nevillehuang** [comment]
Invalid, there are relevant permissions inplace such as `__validateIsOwner()` as seen [here](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1498-L1502)
