### ISSUE TITLE
makumbaoscar - Potential Denial of Service (DoS) Attack due to Unbounded withdrawalCalldata Array Processing in claimPrizes Function

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#37]
makumbaoscar

medium

# Potential Denial of Service (DoS) Attack due to Unbounded withdrawalCalldata Array Processing in claimPrizes Function

## Summary

Winners might have to pay more in transaction fees when claiming prizes in the YoloV2 contract if there are too many prizes to claim at once.

## Vulnerability Detail

The` claimPrizes` function in the YoloV2 contract iterates over each `WithdrawalCalldata[]` in the input array. For each `WithdrawalCalldata[]`, it retrieves the corresponding round and validates that the round has been drawn and that the message sender is the winner. As the size of the `withdrawalCalldata[]` array increases, the gas required to execute the function also increases. This could lead to higher transaction costs for winners when claiming their prizes.

## Impact
Winners may need to pay higher gas fees to claim their prizes if the `withdrawalCalldata []`array is large. This could potentially discourage participation in the contract, as the cost of claiming prizes could outweigh the value of the prizes themselves.

## Code Snippet
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L491-L498

## Tool used

Manual Review

## Recommendation
To mitigate this risk, consider implementing a limit on the size of the `withdrawalCalldata[] `array that the `claimPrizes` function will accept. This will prevent the function from consuming excessive gas and protect winners from potentially high transaction costs.

**Comment by nevillehuang** [comment]
Invalid based on sherlocks [OOG rules](https://docs.sherlock.xyz/audits/judging/judging#viii.-list-of-issue-categories-that-are-considered-valid)

> 4. Out of Gas: Issues that result in Out of Gas errors either by the malicious user filling up the arrays or there is a practical call flow that results in OOG can be considered a valid medium or in cases of blocking all user funds forever maybe a valid high.
Exception: In case the array length is controlled by the trusted admin/owner or the issue describes an impractical usage of parameters to reach OOG state then these submissions would be considered as low.
