### ISSUE TITLE
Cosine - L2 chain reorgs will often change the winner as the `minimumRequestConfirmations` is set to low

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#49]
Cosine

medium

# L2 chain reorgs will often change the winner as the `minimumRequestConfirmations` is set to low

## Summary

When randomness is requested via the chainlink VRF and a reorg happens on the given chain the randomness value can change. This can lead to the fact that the winner of a round changes after the round has already finished.

## Vulnerability Detail

The following facts lead to the bug:

- The protocol uses chainlinks VRF to decide which user wins.
- The contracts will be deployed on L2 chains (Potentially on any EVM-compatible L2 chain)
- The `minimumRequestConfirmations` is set to 3

The `minimumRequestConfirmations` is set to 3, which means that the protocol will wait for 3 confirmations before deciding the winner. On some L2 chains (for example Polygon) reorgs >= 3 are very common (https://polygonscan.com/blocks_forked). Therefore it will happen that for example users are announced as winners, gain the rewards and then suddenly the chain reorgs and the user loses all the rewards.

Here we can see the `_drawWinner` function and that the `minimumRequestConfirmations` is set to 3:

```solidity
function _drawWinner(Round storage round, uint256 roundId) private {
    round.status = RoundStatus.Drawing;
    round.drawnAt = uint40(block.timestamp);

    uint256 requestId = VRF_COORDINATOR.requestRandomWords({
        keyHash: KEY_HASH,
        subId: SUBSCRIPTION_ID,
        minimumRequestConfirmations: uint16(3),
        callbackGasLimit: uint32(500_000),
        numWords: uint32(1)
    });

    if (randomnessRequests[requestId].exists) {
        revert RandomnessRequestAlreadyExists();
    }

    // This is equivalent to
    // randomnessRequests[requestId].exists = true;
    // randomnessRequests[requestId].roundId = uint40(roundId);
    assembly {
        mstore(0x00, requestId)
        mstore(0x20, randomnessRequests.slot)
        let randomnessRequestSlot := keccak256(0x00, 0x40)

        // 1 is true
        sstore(randomnessRequestSlot, or(1, shl(RANDOMNESS_REQUEST__ROUND_ID_OFFSET, roundId)))
    }

    emit RandomnessRequested(roundId, requestId);
    emit RoundStatusUpdated(roundId, RoundStatus.Drawing);
}
```

## Impact

User experience a win and then suddenly losses the rewards. Except from the very bad user experience, this could also lead to different bad consequences.

For example:

- A user who received rewards could calculate with them and participate with a lot of funds in the next round which the user would not have risked without winning. Therefore this bug could bring users into very bad financial decisions.
- A user who received rewards could roll them over to the next round and suddenly is not the winner anymore and missed a round they could have won as the `rolloverETH` call reverted.

## Code Snippet

https://github.com/sherlock-audit/2024-01-looksrare/blob/7d76b96a58a6aee38f23bb38b8a5daa3bdc03f7c/contracts-yolo/contracts/YoloV2.sol#L1004

## Tool used

Manual Review

## Recommendation

Create a variable for the `minimumRequestConfirmations` value to adjust it on different chains and increase the value on chains where bigger reorgs are common.

Duplicate of #41

**Comment by 0xhiroshi** [comment]
https://github.com/LooksRare/contracts-yolo/pull/177
