### ISSUE TITLE
ravikiran.web3 - YoloV2::fulfillRandomWords() function, the fee owned to protocol related computation is wrong

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#5]
ravikiran.web3

high

# YoloV2::fulfillRandomWords() function, the fee owned to protocol related computation is wrong

## Summary
On receipt of the random word from chainlink VRF, the logic identifies the winner of the round. At this time, the logic also
marks the winner of the round and amount of protocol fee owned in the round object. The logic of computing the protocol fee
looks wrong.

## Vulnerability Detail
The protocol fee is computed as below. It does not make sense to use currentEntryIndex.
Instead, it should be count, which represents the number of deposits that were part of the round.
Since protocol facilitated for all the deposits equally, it makes sense to deduct from the final amount being refunded to the winner.

So, to compute the total amount, it would be 
    total amount  =  round.valuePerEntry x count;

On the total amount, applying the protocol fee basis points will arrive as the protocol Fee owned and deducted from the  claim amount or look tokens as applicable. The receiver of reward pays the amount.
 

```solidity
 round.protocolFeeOwed = (round.valuePerEntry * currentEntryIndex * round.protocolFeeBp) / 10_000;
```

## Code Snippet
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1275-L1289

```solidity
  round.protocolFeeOwed = (round.valuePerEntry * currentEntryIndex * round.protocolFeeBp) / 10_000;
```

## Tool used
Manual Review

## Recommendation
Revise the computation of protocolFeeOwed to use count instead of currentEntryIndex as below.
```solidity
  round.protocolFeeOwed = (round.valuePerEntry * count * round.protocolFeeBp) / 10_000;
```

**Comment by nevillehuang** [comment]
Invalid, 1 deposit can have more than 1 entry depending on value of deposit, so intended logic for fee calculation is correct as seen [here](https://github.com/sherlock-audit/2024-01-looksrare/blob/7d76b96a58a6aee38f23bb38b8a5daa3bdc03f7c/contracts-yolo/contracts/YoloV2.sol#L1423), [here](https://github.com/sherlock-audit/2024-01-looksrare/blob/7d76b96a58a6aee38f23bb38b8a5daa3bdc03f7c/contracts-yolo/contracts/YoloV2.sol#L1055), [here](https://github.com/sherlock-audit/2024-01-looksrare/blob/7d76b96a58a6aee38f23bb38b8a5daa3bdc03f7c/contracts-yolo/contracts/YoloV2.sol#L1102) and [here](https://github.com/sherlock-audit/2024-01-looksrare/blob/7d76b96a58a6aee38f23bb38b8a5daa3bdc03f7c/contracts-yolo/contracts/YoloV2.sol#L1174)
