### ISSUE TITLE
zzykxx - `_protocolFeeOwedInLOOKS` returns the wrong amount of LOOKS to pay

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#51]
zzykxx

high

# `_protocolFeeOwedInLOOKS` returns the wrong amount of LOOKS to pay

## Summary
The function [`_protocolFeeOwedInLOOKS()`](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1669-L1676) returns the wrong amount of LOOKS to pay as a fee to the protocol.

## Vulnerability Detail
The protocol allows users to get a discount on the fees they have to pay if they pay in LOOKS. The function responsible for calculating the amount of LOOKS owed is [`_protocolFeeOwedInLOOKS()`](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1669-L1676) and it does so based on the value of the `protocolFeeDiscountBp` variable:
```solidity
protocolFeeOwedInLOOKS = (1e18 * protocolFeeOwedInETH * protocolFeeDiscountBp) / erc20Oracle.getTWAP(LOOKS, uint32(TWAP_DURATION)) / 10_000;
```

As an example if the variable `protocolFeeDiscountBp` is set to `3_000` users are supposed to get a 30% discount when paying with LOOKS, but they get a 70% discount instead. The easiest way to see why this is the case is by thinking about what would happen if users were supposed to receive a 0% discount (ie. `protocolFeeDiscountBp` set to 0):
```solidity
protocolFeeOwedInLOOKS = (1e18 * protocolFeeOwedInETH * 0) / erc20Oracle.getTWAP(LOOKS, uint32(TWAP_DURATION)) / 10_000
```

`1e18 * protocolFeeOwedInETH * 0` would return 0 and as a consequence `protocolFeeOwedInLOOKS` would be 0, meaning users would pay 0 LOOKS when they are supposed to not receive a discount and pay the full amount.

## Impact

Users might overpay/underpay fees when paying with LOOKS and the protocol might receive more or fewer fees than it should based on the value of `protocolFeeDiscountBp`. 

## Code Snippet
- [`_protocolFeeOwedInLOOKS()`](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1669-L1676)
## Tool used

Manual Review

## Recommendation

Correct the code to:
```solidity
protocolFeeOwedInLOOKS = (1e18 * protocolFeeOwedInETH * (10_000 - protocolFeeDiscountBp)) / erc20Oracle.getTWAP(LOOKS, uint32(TWAP_DURATION)) / 10_000;
```

**Comment by zzykxx** [comment]
Escalate

I'm not sure if this has been looked at properly since only the "Excluded" label is here. Unless the protocol team intended `protocolFeeDiscountBp` to indicate the discount from the point of the protocol instead of the point of view of the user this should be considered valid because the fee is calculated incorrectly, which constitutes either a loss for the protocol or for the user.

As stated in the report setting a discount of `0%` (ie. `protocolFeeDiscountBp = 0`), which should result in the user paying the whole fee (since there is no discount) will end up with the user paying 0 LOOKS instead, a `100%` discount.

If the protocol team coded the function to work this way on purpose then this should be invalid.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I'm not sure if this has been looked at properly since only the "Excluded" label is here. Unless the protocol team intended `protocolFeeDiscountBp` to indicate the discount from the point of the protocol instead of the point of view of the user this should be considered valid because the fee is calculated incorrectly, which constitutes either a loss for the protocol or for the user.
> 
> As stated in the report setting a discount of `0%` (ie. `protocolFeeDiscountBp = 0`), which should result in the user paying the whole fee (since there is no discount) will end up with the user paying 0 LOOKS instead, a `100%` discount.
> 
> If the protocol team coded the function to work this way on purpose then this should be invalid.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by jpopxfile** [comment]
This is intended to work this way, we renamed the variable to `_updateDiscountedProtocolFeeBp` to make it less confusing.

https://github.com/LooksRare/contracts-yolo/pull/206

**Comment by nevillehuang** [comment]
Invalid, intended logic, 0% means they pay nothing so no fees is owed to protocol represented by `protocolFeeOwedInLOOKS`

**Comment by Czar102** [comment]
Given sponsor's and Lead Judge's comments, I'm planning to reject the escalation and leave the issue as is.

**Comment by zzykxx** [comment]
forgot to remove escalation, this is 100% invalid

**Comment by Czar102** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [zzykxx](https://github.com/sherlock-audit/2024-01-looksrare-judging/issues/51/#issuecomment-1919425996): rejected
