### ISSUE TITLE
LTDingZhen - Users withdraw half of their ETH even if token outflow is not allowed

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#53]
LTDingZhen

medium

# Users withdraw half of their ETH even if token outflow is not allowed

## Summary

function `rolloverETH` is not protected by `_validateOutflowIsAllowed()`, enables it to be abused to withdraw funds after admin calls `toggleOutflowAllowed()`.

## Vulnerability Detail

In Yolo v2, functions that involve playing rounds are protected by `whenNotPaused` and functions that involve withdrawing are protected by `_validateOutflowIsAllowed`. `rolloverETH` is used to rollover ETH from prev rounds to the current round, so it is protected by `whenNotPaused`. However, this is not enough because the dust-refund mechanism can be abused:

        uint256 roundValuePerEntry = round.valuePerEntry;
        uint256 dust = rolloverAmount % roundValuePerEntry;
        if (dust != 0) {
            unchecked {
                rolloverAmount -= dust;
            }
            _transferETHAndWrapIfFailWithGasLimit(WETH, msg.sender, dust, gasleft());
        }

As there is a check that forbid 0-value deposit:

     if (rolloverAmount < roundValuePerEntry) {
            revert InvalidValue();
     }

Since protocol fee is subtracted from `rolloverAmount` , for a minimum `rolloverAmount` = `2*roundValuePerEntry` , `1*roundValuePerEntry` would be deposited into next round, and '1*roundValuePerEntry - fee' would be sent to the caller.

So, an user can split his balance into several `2*roundValuePerEntry` (0.02ETH), and then call `rolloverETH` many times to withdraw half of his deposits/prizes. (before deducting protocol fees), and deposit his ETH into next round.

## Impact

Users can withdraw (close to) half of their ETH prizes and withdrawable deposits even when `outflowAllowed = false`.

## Code Snippet

https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L643-L743

## Tool used

Manual Review

## Recommendation

Add `_validateOutflowIsAllowed()` on `rolloverETH`.

##Note for judge

I believe this issue should be judged as medium since it breaks a core protocol functionality, and it breaks the consistence between ETH and ERC20, ERC721 deposits, which creates privileges for some users.

Duplicate of #103

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  valid: users can bypass the outflow check; medium(10)
