### ISSUE TITLE
LTDingZhen - Constraint `MAXIMUM_NUMBER_OF_DEPOSITS_PER_ROUND` can be bypassed easily

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#59]
LTDingZhen

high

# Constraint `MAXIMUM_NUMBER_OF_DEPOSITS_PER_ROUND` can be bypassed easily

## Summary

MAXIMUM_NUMBER_OF_DEPOSITS_PER_ROUND can be bypassed.

## Vulnerability Detail

In Yolo v2, there are three ways to deposit into a round: by calling function `rolloverETH()` or by calling function `deposit` or by calling `depositETHIntoMultipleRounds`. However, the three functions use different validation: `deposit` makes sure that the number of deposits never exceeds MAXIMUM_NUMBER_OF_DEPOSITS_PER_ROUND:

    function _deposit(uint256 roundId, DepositCalldata[] calldata deposits) private {
        ...
        if (roundDepositCount > MAXIMUM_NUMBER_OF_DEPOSITS_PER_ROUND) {
            revert MaximumNumberOfDepositsReached();
        }
        ...
    }

But there is no such constraint on `rolloverETH()` and 'depositETHIntoMultipleRounds', which means anyone can create a deposit in ETH and push `roundDepositCount` to some value above `MAXIMUM_NUMBER_OF_DEPOSITS_PER_ROUND`!

## Impact

Firstly, this issue destroys a basic constraint of the game, and it is very likely to occur because it would be easily triggered during normal user interactions.

Secondly, in Yolo v2's design, the last depositor in a round is responsible for calling `_drawWinner` to get a random number from Chainlink. Howrver, after `roundDepositCount > MAXIMUM_NUMBER_OF_DEPOSITS_PER_ROUND`, '_shouldDrawWinner' would always return false, so the game won't stop as expected, and continue to accept deposits from `rolloverETH()` and `depositETHIntoMultipleRounds`, until someone calls `drawWinner`.

    function _shouldDrawWinner(
        uint256 numberOfParticipants,
        uint256 maximumNumberOfParticipants,
        uint256 roundDepositCount
    ) private pure returns (bool shouldDraw) {
        shouldDraw =
            numberOfParticipants == maximumNumberOfParticipants ||
            (numberOfParticipants > 1 && roundDepositCount == MAXIMUM_NUMBER_OF_DEPOSITS_PER_ROUND);
    }

Thirdly, LookRare have to pay more gas to keep the game running.

Finally, this vulnerability provides privileges to some users, for there is no limit to their deposits. Consider the following scenario: 

Alice accidentally deposited a high rarity NFT as a bet in the game.

Alice noticed her mistake, then she deposited a large amount of ETH into the current round.

Bob knows this issue, so he can always guarantee himself a higher probability of getting this NFT.

## Code Snippet

https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1221

## Tool used

Manual Review

## Recommendation
just add the check on  `rolloverETH()` and `depositETHIntoMultipleRounds`

Duplicate of #78

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  valid because {valid: attacker can prevent the round from drawing due to bypass of max deposit;high(2)}
