### ISSUE TITLE
radin200 - `YoloV2::claimPrizes` misses msg.value check

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-01-looksrare-judging#64]
radin200

medium

# `YoloV2::claimPrizes` misses msg.value check

## Summary
Mishandling msg.value may lead to YoloV2 fund reduction

## Vulnerability Detail
When anybody calls YoloV2.claimPrizes with second parameter false and value = 0, could force YoloV2 to pay the round fees only if protocolFeeOwed <= ethAmount
```javascript
function claimPrizes(
        WithdrawalCalldata[] calldata withdrawalCalldata,
        bool payWithLOOKS
    ) external payable nonReentrant {

    ...
    ...
    ...
                protocolFeeOwed -= msg.value;
                if (protocolFeeOwed <= ethAmount) {
                    unchecked {
                        ethAmount -= protocolFeeOwed;
                    }
                } else {
                    revert ProtocolFeeNotPaid();
                }
            }
        }
```

## Impact
Lose of funds

## Code Snippet
https://github.com/sherlock-audit/2024-01-looksrare/blob/7d76b96a58a6aee38f23bb38b8a5daa3bdc03f7c/contracts-yolo/contracts/YoloV2.sol#L473-L544

## Tool used

Manual Review

## Recommendation
Consider adding msg.value check right after payWithLOOKS check

Example:
```javascript
if (payWithLOOKS) {
            if (msg.value != 0) {
                revert InvalidValue();
            }
+      }else{
+      if (msg.value == 0) {
+          revert();
+          }
+     }
        for (uint256 i; i < withdrawalCalldata.length; ++i) {
```

**Comment by nevillehuang** [comment]
Invalid, user input error, they should not be sending ETH if they want to pay fees with LOOKS
