### ISSUE TITLE
novaman33 - Deploying on EVM compatible L2 ZK chains will be problematic

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#65]
novaman33

high

# Deploying on EVM compatible L2 ZK chains will be problematic

## Summary
Deploying to some L2 chains will cause problems with the storage composition.
## Vulnerability Detail
In the Context Q&A, it is mentioned that the project is potentially going to be deployed "any EVM compatible L2 (Including ZK L2s)". However as the documentation of ZKSync states: "EVM Compatible means that a percentage of the opcodes of Ethereum’s EVM are supported; thus, a percentage of smart contracts work out of the box." This means that some opcodes will behave differently. For example: https://docs.zksync.io/build/developer-reference/differences-with-ethereum.html#mstore-mload 
"Unlike EVM, where the memory growth is in words, on zkEVM the memory growth is counted in bytes. For example, if you write mstore(100, 0) the msize on zkEVM will be 132, but on the EVM it will be 160. Note, that also unlike EVM which has quadratic growth for memory payments, on zkEVM the fees are charged linearly at a rate of 1 erg per byte." 
## Impact
Problems with the storage composition. Invalid data reading
## Code Snippet
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol?plain=1#L1683-1687
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol?plain=1#L1700

## Tool used

Manual Review

## Recommendation
Even though a chain states that it is EVM compatible, problems including assembly and opcodes should be carefully fixed before deployment.

**Comment by nevillehuang** [comment]
Invalid, no actual issue highlighted here specific to contract logic
