### ISSUE TITLE
ravikiran.web3 - YoloV2::cancelAfterRandomnessRequest() will not work, user funds will be locked for ever

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#7]
ravikiran.web3

high

# YoloV2::cancelAfterRandomnessRequest() will not work, user funds will be locked for ever

## Summary
YoloV2::cancelAfterRandomnessRequest() will not serve the purpose of being able to cancel the round incase the VRF notification did not come back in a day. This will result in permanently locking the funds of the end user.

## Vulnerability Detail
cancelAfterRandomnessRequest() allows the owner of the contract the mark the round as cancelled incase the VRF notification did not come back from chain link. Cancelling the round will allow the user to withdraw their deposited tokens.

It is important to note that the waiting period for cancelling is one day. Even owner cannot cancel before the waiting period.

The problem arises from the logic of cancelAfterRandomnessRequest() which relies on roundsCount state variable.
Every time a new round is created, the roundsCount will be incremented. As such, there is a very low chance that there were no rounds created in a period of one day and hence, 

The vulnerabilities are:
a) Since a new round can be created depending on the engagement, the possibility for cancelling the round that did not receive the VRF call back is low. As such, the user funds are permanently locked in the round as it will not transit from Drawing to any other state. While in drawing state, the funds cannot be withdrawn and hence locked. 
     
b) there is a huge risk of owner cancelling some other round that is still valid and waiting for notification from VRF and by calling this function, marks the round as cancelled.

Since the fulfillRandomWords will check for Drawing to process, even when the event was received, it will be accounted as not received and qualifies for one more round to have user funds locked. This can reoccur across rounds and have serve implications. 

## Impact
User funds are locked permanently. It could have for many rounds as well.

## Code Snippet
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L451-L468

Since the function operates on roundsCount,  either it will revert due to invalid round status or mark some other rounds as cancelled.

```solidity
uint256 roundId = roundsCount;
        Round storage round = rounds[roundId];

        _validateRoundStatus(round, RoundStatus.Drawing);

        if (block.timestamp < round.drawnAt + 1 days) {
            revert DrawExpirationTimeNotReached();
        }

        round.status = RoundStatus.Cancelled;

```
## Tool used

Manual Review

## Recommendation
Pass roundId as parameter to the function. As the function can be called by owner only, that should resolve the issue.

**Comment by nevillehuang** [comment]
Invalid, users can always withdraw funds from cancelled rounds via `withdrawDeposits()`
