### ISSUE TITLE
zraxx - The ERC721 tokens deposited by users cannot obtain equivalent `entriesCount`, which reduces the user's probability of winning.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#77]
zraxx

medium

# The ERC721 tokens deposited by users cannot obtain equivalent `entriesCount`, which reduces the user's probability of winning.

## Summary

The ERC721 tokens deposited by users cannot obtain equivalent `entriesCount`, which reduces the user's probability of winning.

## Vulnerability Detail

Function `deposit` allows users to deposit ERC721 tokens and obtain corresponding `entriesCount`, which represents the probability of winning. However, when calculating `entriesCount`, the protocol directly ignores the remainder, which leads to users can not be able to obtain equivalent entriesCount when depositing multiple ERC721 tokens.

For example, when `round.valuePerEntry` = 10 and the price of ERC721 tokenX = 19, Bob deposits 20 tokenX. According to the protocol, Bob's `entriesCount` will be equal to 20 (19/10\*20=20). However, under normal circumstances, Bob's `entriesCount` should be equal to 38 (19\*20/10=38). This means that Bob's probability of winning is reduced by about 47% ((38-20)/38).

## Impact

The user's probability of winning will be reduced and unable to match their deposited amount.

## Code Snippet

https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1096-L1155

## Tool used

Manual Review

## Recommendation

The remainder between the ERC721 price and round.valuePerEntry should be handled correctly instead of ignored.

Duplicate of #11

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  valid: probability rate will be low; medium(4)
