### ISSUE TITLE
vvv - DoS attack by depositETHIntoMultipleRounds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#81]
vvv

high

# DoS attack by depositETHIntoMultipleRounds

## Summary

`depositETHIntoMultipleRounds` could be used to block any rounds opennings and even block admin rounds cancelations. We can call `depositETHIntoMultipleRounds` with zero `amounts` (however we should pass at least one non-zero `amount`), and with the sufficient number of such calls we fill any future round with zero deposits, thus blocking the drawing. 

## Vulnerability Detail

`depositETHIntoMultipleRounds` method could be called with several zero `amounts`, this method only checks the total sum to be positive. This way we can fill any future or current round with zero deposits from multiple accounts, blocking the `fulfillRandomWords` method, as  [`currentEntryIndex` will be zero](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1287) in this case. It leads to at least one day blockage of round advancing, which can be repeated any time. 

We can even block the admin round cancelations by filling the sufficient number of round with zero deposits. In `cancel` method admin cancels rounds in loop and starts new round after that. We can block as many rounds as possible to make the cancelation run out of gas. Admin cancelation couldn't be done partially, since [it starts new round after cancelation](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L445), which in this case would lead to [invalid data in round structure](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L976-L986). 

## Impact

Total blockage of contract logic. 

## Code Snippet

https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L312-L362

https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L429-L446

## Tool used

Manual Review

## Recommendation

Check for zero deposits in `depositETHIntoMultipleRounds` method

Duplicate of #18

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  valid: attacker can cause DOS; high(1)
