### ISSUE TITLE
vvv - Prize could be stolen by exploting depositETHIntoMultipleRounds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#83]
vvv

high

# Prize could be stolen by exploting depositETHIntoMultipleRounds

## Summary

`depositETHIntoMultipleRounds` could be used to place zero deposits in round. Zero deposits lead to duplicated items in `currentEntryIndexArray` array in `fulfillRandomWords`, and this array then used in `findUpperBound` function. This function produces incorrect results with duplicated items, it could select arbitrary duplicated element, which in this case could belong to the attacker. 

## Vulnerability Detail

`depositETHIntoMultipleRounds` method could be called with several zero amounts, this method only checks the total sum to be positive. This way we can place zero deposits on any future or current rounds. [Zero deposits doesn't change `currentEntryIndex`](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1659-L1660), thus leading to [duplicated items in `currentEntryIndexArray` array](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1281-L1284) in `fulfillRandomWords` method. `currentEntryIndexArray` then is used in `findUpperBound` function, which doens't correctly work with duplicated comments as it's [said in the comments](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/libraries/Arrays.sol#L17-L20). For example, `findUpperBound([10, 20, 20, 20, 20], 20)` returns 4, which in the case of zero deposists would belong to the attacker. When `winningEntry` happens to equal the exact amount of `currentEntryIndex`, it leads to possible attack, where attacker steal all the bets without any bet from themself. 

This behaviour leads to slealing the round prize without betting any money. The probability of funds being stolen depends on the volume of bets. In extreme cases, this probability can be 50%. 

## Impact

Possible steal of round prize.

## Code Snippet

https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L312-L362

https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1270-L1296

## Tool used

Manual Review

## Recommendation

Check for zero deposits in depositETHIntoMultipleRounds method

Duplicate of #18

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  valid: users can losse funds; high(1)
