### ISSUE TITLE
4b - In `YoloV2::claimPrizes` and `YoloV2::rolloverETH` the transfer of `protocolFeeOwed` with LOOKS  is unhandled and can lead to loss of funds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#87]
4b

medium

# In `YoloV2::claimPrizes` and `YoloV2::rolloverETH` the transfer of `protocolFeeOwed` with LOOKS  is unhandled and can lead to loss of funds

## Summary
In `YoloV2::claimPrizes` and `YoloV2::rolloverETH`  when transferring LOOKS token to the fees recipient there's no code to validate this transfer whether it fails or it is a success, this can lead to an usual behaviour of the protocol.

## Vulnerability Detail
In `YoloV2::claimPrizes`  whenever we check the code
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L512-L519
we will notice that there is no error validation code to check whether the transaction was a success or failure neither is there code to check the return value of the transaction.

In `YoloV2::rolloverETH` too the same thing applies there at [line 698](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L698) after the transfer,  no error/ validation was checked, the only check that was implemented was in the next else statement  which does not apply when the first if condition is true.

```solidity
        if (protocolFeeOwed != 0) {
            if (payWithLOOKS) {
                protocolFeeOwed = _protocolFeeOwedInLOOKS(protocolFeeOwed);
@-->                transferManager.transferERC20(LOOKS, msg.sender, protocolFeeRecipient, protocolFeeOwed);

                emit ProtocolFeePayment(protocolFeeOwed, LOOKS);
            } else {
@-->                if (rolloverAmount < protocolFeeOwed) {
                    revert ProtocolFeeNotPaid();
                } else {
                    unchecked {
                        rolloverAmount -= protocolFeeOwed;
                    }
                }

                _transferETHAndWrapIfFailWithGasLimit(WETH, protocolFeeRecipient, protocolFeeOwed, gasleft());

                emit ProtocolFeePayment(protocolFeeOwed, address(0));
            }
        }
```
## Impact
Handling token transactions is a good practice that needs to be observed but aside that if this transaction reverts due to some error there will be no error handling code to catch this error which will interfere with the operation of the protocol, and can eventually lead to loss of funds.

## Code Snippet
`YoloV2::claimPrizes` 
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L473-L534

`YoloV2::rolloverETH`
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L643-L714

## Tool used

Manual Review

## Recommendation
Implement error handling code in case the transfer fails or you can implement the SafeTransferERC20().

**Comment by nevillehuang** [comment]
Invalid, out of scope. The logic for function `transferERC20` is only present in mock contracts and not actual in scope contracts, and since not exposed, code logic cannot be assumed.
