### ISSUE TITLE
4b - No Zero Address checks when transferring `transferAccumulator.amount`  and this can lead to lock up of funds

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-01-looksrare-judging#88]
4b

medium

# No Zero Address checks when transferring `transferAccumulator.amount`  and this can lead to lock up of funds

## Summary
_executeERC20DirectTransfer does not perform any zero checks before transfer.
## Vulnerability Detail
Before `transferAccumulator.amount` is being sent, there are no zero checks performed which can lead to transfering to an invalid address.

## Impact
This can lead to lock up of funds.
## Code Snippet

https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L536

https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L630

https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1482-L1489

## Tool used

Manual Review

## Recommendation
Zero address checks should be implemented before transaction is done

**Comment by nevillehuang** [comment]
Invalid based on sherlock [rules](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid)

> 3. Zero address checks: Check to make sure input values are not zero addresses.
