### ISSUE TITLE
mstpr-brainbot - Users can deposit with ERC20 to get cheaper entry tickets

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-01-looksrare-judging#90]
mstpr-brainbot

medium

# Users can deposit with ERC20 to get cheaper entry tickets

## Summary
Users can deposit ERC20 tokens in the current round. When they do, the TWAP is determined from the first ERC20 deposit that occurred in that round with that specific token. If such a deposit hasn't occurred yet, the current TWAP is used to price the token. There's a 10-minute interval before the next round starts. Within this time frame, someone can wait until the last minute to observe whether the recorded TWAP price is higher or lower in the current market. They can then swap to the token and make their deposit accordingly.
## Vulnerability Detail
Suppose the price of 1 WETH is 10,000 LOOKS at the beginning of the round, and the TWAP also indicates 10,000 LOOKS. Alice deposits 10,000 LOOKS into the round, assuming the value per entry is 1 ETH. Consequently, Alice receives 1 entry ticket, and the round's LOOKS price is set at 10,000 LOOKS = 1 ETH.

Now, anyone wishing to deposit LOOKS will be assessed based on this price set by the game. However, within the next 10 minutes, the LOOKS price decreases, and in the current market, 1 ETH is equivalent to 11,000 LOOKS. Despite this change, the game still assumes the rate of 1 ETH to be 10,000 LOOKS.

Bob notices this and holds 1 ETH. Instead of depositing 1 ETH to obtain 1 ticket, Bob opts to sell 0.9 ETH for 10,000 LOOKS. He deposits this amount into the round, securing 1 entry ticket, and retains the remaining 0.1 ETH in his wallet.

In essence, individuals looking to deposit ERC20 tokens in the round can wait until the last minute to make a more economical deposit compared to using ETH. If the token price rises, the user has the option to forgo the deposit.
## Code Snippet
https://github.com/sherlock-audit/2024-01-looksrare/blob/7d76b96a58a6aee38f23bb38b8a5daa3bdc03f7c/contracts-yolo/contracts/YoloV2.sol#L1161-L1216
## Tool used

Manual Review

## Recommendation
I believe the most effective approach is to fetch the price each time a user makes a deposit. TWAP may not be the most suitable method for this situation. I would recommend using Chainlink oracles because the tokens intended for use are already tokens with decent liquidity, implying that most of them likely have Chainlink price feeds. Chainlink can update prices through two methods: a heartbeat and price deviation. If the price undergoes significant changes, Chainlink will update its price, eliminating the potential issue described above.

**Comment by 0xhiroshi** [comment]
1. There isn't a Chainlink price feed for LOOKS
2. We are using 1 hour TWAP
3. We think it's fairer to lock in the price of an ERC-20 / ERC-721 for each round on the first deposit
4. Our round duration on L2 will be very short, between 1 and 5 minutes

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  valid: medium(5)

**Comment by nevillehuang** [comment]
Invalid, this is seeming a duplicate of #50, but is actually describing normal arbitrage behavior with no loss of potential entries by user. Additionally, like sponsor mentioned, there is no chainlink price feed for LOOKs.
