### ISSUE TITLE
lil.eth - Unnecessary outflowAllowed Check in Round Management Functions

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-01-looksrare-judging#92]
lil.eth

medium

# Unnecessary outflowAllowed Check in Round Management Functions

## Summary

`outflowAllowed` modifier call in the `cancel` and `cancelAfterRandomnessRequest` functions restrict users from cancelling the yolo game without adding some security features, preventing users from continuing to play the game

## Vulnerability Detail
```solidity
function cancel() external nonReentrant {
    _validateOutflowIsAllowed();
    ...
}

function cancelAfterRandomnessRequest() external nonReentrant {
    _validateOutflowIsAllowed();
    ...
}
```
Typically, such a check is used to prevent unauthorized withdrawal or transfer of funds. However, these particular functions are designed for managing the state of the game rounds, not for transferring funds out of the contract.
However functions where outflow needs to be check (`claimPrizes()` and `withdrawDeposits()`) already implements this check : 
```solidity
function claimPrizes(
        WithdrawalCalldata[] calldata withdrawalCalldata,
        bool payWithLOOKS
    ) external payable nonReentrant {
        _validateOutflowIsAllowed();
        ...
}
    
function withdrawDeposits(WithdrawalCalldata[] calldata withdrawalCalldata) external nonReentrant {
        _validateOutflowIsAllowed();
       ...
}
```

## Impact
Inclusion of `outflowAllowed` in these round management functions prevents users from starting a new round in case it is needed (no enough users, VRF not fulfilled within 24 hours) and block the game without adding some security features

## Code Snippet

https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L422
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L452
## Tool used

Manual Review

## Recommendation
Remove `outflowAllowed` check from `cancel()` and `cancelAfterRandomnessRequest()`

**Comment by nevillehuang** [comment]
Invalid, admins can toggle whether or not this functions can be cancelled, so this would be invalid based on sherlock [rules see point 5.](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid)
