### ISSUE TITLE
pash0k - NFT oracle price manipulation

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-looksrare-judging#95]
pash0k

medium

# NFT oracle price manipulation

## Summary
The Reservoir oracle price can be quite easily manipulated, which may result in potential loss of funds for certain users or in inabilty to use some NFT collections for depositing in a round.

## Vulnerability Detail
As the Yolo contract requests the TWAP for the floor price of an NFT collection from Reservoir, it exposes an attack vector. Malicious user may buy an NFT from certain collection and list it a very low price on some marketplace, which is supported by Reservoir. Let's name this listing price `maliciousPrice` for convenience. 

If one tries to buy the NFT, the attacker can just frontrun, cancel the order, and after the execution of a buy attempt transaction (which will fail), re-list the NFT. This way the malicious user is able to hold the floor of the collection at a very low price for a certain period of time, which will result in a low price provided by the Reservoir oracle. 

For example, if TWAP period is 1 day and real floor price is 0.1 ETH, it is sufficient for the attacker to hold the floor at 0.001 ETH for 8 hours to drive the price provided by the oracle to 0.067 ETH, which is a 33% decrease.

The costs of such actions are quite low compared to a possible NFT price and can be driven even lower by executing the floor dumping on some unpopular marketplace which is still supported by Reservoir (on unpopular marketplaces there will be less buy attempts, so, less costs for the attacker). The costs are essentially only gas expences and NFT price (which can be later sold by the attacker).

There is no contradiction in this vulnerability with "NFT floor prices provided by Reservoir are expected to be trusted and will be used to value any token id in the same collection", which was said by the team. The prices provided by the oracle will be real in this case, but they are manipulated and inaccurate for estimating NFT price.

## Impact

There are two possible impacts:

1) If the `maliciousPrice` <  `valuePerEntry`, then the whole NFT collection cannot be used for participating in the game, so users won't be able to deposit their NFTs.

2) If `maliciousPrice` >= `valuePerEntry`, then players will be able to deposit their NFTs, but the `entriesCount` for their deposit will be far less than it should have been were the NFTs priced accurately. This results in unfairness, as the winning possibility for NFT depositors is lowered, which may lead to loss of funds.

## Code Snippet

use of `_getReservoirPrice` in function `_deposit`:
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1098-L1099

function `_getReservoirPrice`:
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1635-L1643

function `_verifyReservoirSignature`:
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1600-L1629

## Tool used

Manual Review

## Recommendation

I suggest to use not the floor price, but, for example, average price of 5 cheapest NFTs listed, as it will increase costs of the attack several times.

**Comment by nevillehuang** [comment]
Invalid, given it is explicitly mentioned in the contest details that:

> NFT floor prices provided by Reservoir are expected to be trusted and will be used to value any token id in the same collection.

From discussions by sponsors with gelato:

> From Reservoir: Holding the floor of a collection that low artificially is not really possible, especially for the period of time suggested in the issue. If someone lists at a low price, people will buy (assuming the collection is actively traded). The argument that the seller will simply cancel when someone tries to buy doesn't really hold given that you could use private mempools to relay the buy tx
